// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `native`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProtocolAddress>>
abstract class ProtocolAddress implements RustOpaqueInterface {
  /// Get the device ID of this address.
  int deviceId();

  /// Get the name (user identifier) of this address.
  String name();

  /// Create a new protocol address.
  ///
  /// # Arguments
  /// * `name` - The user identifier (typically a phone number or UUID)
  /// * `device_id` - The device identifier (must be 1-127)
  factory ProtocolAddress({required String name, required int deviceId}) =>
      RustLib.instance.api.crateApiAddressProtocolAddressNew(
        name: name,
        deviceId: deviceId,
      );
}
