// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `native`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PreKeyBundle>>
abstract class PreKeyBundle implements RustOpaqueInterface {
  /// Get the device ID.
  int deviceId();

  /// Get the identity public key.
  Uint8List identityKey();

  /// Get the Kyber pre-key ID.
  int kyberPreKeyId();

  /// Get the Kyber pre-key public key.
  Uint8List kyberPreKeyPublic();

  /// Get the Kyber pre-key signature.
  Uint8List kyberPreKeySignature();

  /// Create a new pre-key bundle from serialized keys.
  ///
  /// # Arguments
  /// * `registration_id` - The registration ID
  /// * `device_id` - The device ID
  /// * `pre_key_id` - The pre-key ID (None for no pre-key)
  /// * `pre_key_public` - The pre-key public key bytes (None for no pre-key)
  /// * `signed_pre_key_id` - The signed pre-key ID
  /// * `signed_pre_key_public` - The signed pre-key public key bytes
  /// * `signed_pre_key_signature` - The signature of the signed pre-key
  /// * `identity_key` - The identity public key bytes
  /// * `kyber_pre_key_id` - The Kyber pre-key ID (required by libsignal)
  /// * `kyber_pre_key_public` - The Kyber pre-key public key bytes (required by libsignal)
  /// * `kyber_pre_key_signature` - The Kyber pre-key signature (required by libsignal)
  factory PreKeyBundle({
    required int registrationId,
    required int deviceId,
    int? preKeyId,
    Uint8List? preKeyPublic,
    required int signedPreKeyId,
    required List<int> signedPreKeyPublic,
    required List<int> signedPreKeySignature,
    required List<int> identityKey,
    required int kyberPreKeyId,
    required List<int> kyberPreKeyPublic,
    required List<int> kyberPreKeySignature,
  }) => RustLib.instance.api.crateApiBundlePreKeyBundleNew(
    registrationId: registrationId,
    deviceId: deviceId,
    preKeyId: preKeyId,
    preKeyPublic: preKeyPublic,
    signedPreKeyId: signedPreKeyId,
    signedPreKeyPublic: signedPreKeyPublic,
    signedPreKeySignature: signedPreKeySignature,
    identityKey: identityKey,
    kyberPreKeyId: kyberPreKeyId,
    kyberPreKeyPublic: kyberPreKeyPublic,
    kyberPreKeySignature: kyberPreKeySignature,
  );

  /// Get the pre-key ID (returns None if no pre-key).
  int? preKeyId();

  /// Get the pre-key public key (returns None if no pre-key).
  Uint8List? preKeyPublic();

  /// Get the registration ID.
  int registrationId();

  /// Get the signed pre-key ID.
  int signedPreKeyId();

  /// Get the signed pre-key public key.
  Uint8List signedPreKeyPublic();

  /// Get the signed pre-key signature.
  Uint8List signedPreKeySignature();
}
