// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Derive keys using HKDF (HMAC-based Key Derivation Function).
///
/// # Arguments
/// * `output_length` - The length of the output key material in bytes
/// * `input_key_material` - The input key material (IKM)
/// * `salt` - Optional salt value (can be empty)
/// * `info` - Optional context/application-specific info (can be empty)
///
/// # Returns
/// The derived key material of the specified length
///
/// # Security
/// Input key material and salt are securely zeroized after use, even on error.
/// The `info` parameter is not zeroized as it's application context (RFC 5869), not a secret.
///
/// Note: `input_key_material` and `salt` are the only copies this function owns.
/// `Hkdf::new` derives a pseudorandom key from them and keeps it inside its own
/// `Hmac` state, and **that copy is not cleared when the `Hkdf` value is
/// dropped** — an earlier version of this note claimed it was, and it was
/// wrong. Three facts decide it: `hkdf` 0.13 publishes no `[features]` at all,
/// `hmac` 0.13 does have `zeroize = ["digest/zeroize"]`, and nothing in this
/// crate's graph turns it on. So dropping an `Hkdf` runs no zeroizing `Drop`;
/// it simply releases the memory for reuse.
///
/// The exposure is bounded — the value lives for one call and never leaves the
/// stack — but it is not zero, and callers deriving long-lived secrets should
/// know the difference. Closing it properly means depending on `hmac` directly
/// with its `zeroize` feature, which changes the dependency graph and so has to
/// be gated on `make build-web` before it can be believed.
Uint8List hkdfDerive({
  required int outputLength,
  required List<int> inputKeyMaterial,
  required List<int> salt,
  required List<int> info,
}) => RustLib.instance.api.crateApiCryptoHkdfDerive(
  outputLength: outputLength,
  inputKeyMaterial: inputKeyMaterial,
  salt: salt,
  info: info,
);

/// Compare two scannable fingerprint encodings.
///
/// # Arguments
/// * `fingerprint1` - First scannable encoding
/// * `fingerprint2` - Second scannable encoding
///
/// # Returns
/// True if the fingerprints match, false otherwise.
bool fingerprintCompare({
  required List<int> fingerprint1,
  required List<int> fingerprint2,
}) => RustLib.instance.api.crateApiCryptoFingerprintCompare(
  fingerprint1: fingerprint1,
  fingerprint2: fingerprint2,
);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Aes256GcmSiv>>
abstract class Aes256GcmSiv implements RustOpaqueInterface {
  /// Decrypt ciphertext with the given nonce and associated data.
  ///
  /// # Arguments
  /// * `ciphertext` - The data to decrypt
  /// * `nonce` - 12-byte nonce (same as used for encryption)
  /// * `associated_data` - Additional authenticated data (same as used for encryption)
  ///
  /// # Security
  /// The returned plaintext may contain sensitive data. The caller is responsible
  /// for securely handling and zeroing the plaintext when done. This is intentional:
  /// the application knows the sensitivity of its data better than this library.
  /// Consider using `SecureBytes.wrap()` on the Dart side if the plaintext is sensitive.
  Uint8List decrypt({
    required List<int> ciphertext,
    required List<int> nonce,
    required List<int> associatedData,
  });

  /// Encrypt plaintext with the given nonce and associated data.
  ///
  /// # Arguments
  /// * `plaintext` - The data to encrypt
  /// * `nonce` - 12-byte nonce (must be unique for each encryption)
  /// * `associated_data` - Additional authenticated data (not encrypted)
  Uint8List encrypt({
    required List<int> plaintext,
    required List<int> nonce,
    required List<int> associatedData,
  });

  /// Create a new AES-256-GCM-SIV cipher with the given key.
  ///
  /// # Arguments
  /// * `key` - The 32-byte encryption key
  ///
  /// # Security
  /// The key is securely zeroized after cipher creation, even on error.
  factory Aes256GcmSiv({required List<int> key}) =>
      RustLib.instance.api.crateApiCryptoAes256GcmSivNew(key: key);
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Fingerprint>>
abstract class Fingerprint implements RustOpaqueInterface {
  /// Create a copy of this fingerprint.
  Fingerprint cloneFingerprint();

  /// Get the display string representation of this fingerprint.
  ///
  /// Returns a 60-digit numeric string formatted as 12 groups of 5 digits.
  String displayString();

  /// Create a new fingerprint for comparing identity keys.
  ///
  /// # Arguments
  /// * `iterations` - Number of iterations for fingerprint generation
  /// * `version` - Fingerprint protocol version
  /// * `local_identifier` - Local identity (e.g., phone number bytes)
  /// * `local_public_key` - Local identity public key bytes
  /// * `remote_identifier` - Remote identity (e.g., phone number bytes)
  /// * `remote_public_key` - Remote identity public key bytes
  factory Fingerprint({
    required int iterations,
    required int version,
    required List<int> localIdentifier,
    required List<int> localPublicKey,
    required List<int> remoteIdentifier,
    required List<int> remotePublicKey,
  }) => RustLib.instance.api.crateApiCryptoFingerprintNew(
    iterations: iterations,
    version: version,
    localIdentifier: localIdentifier,
    localPublicKey: localPublicKey,
    remoteIdentifier: remoteIdentifier,
    remotePublicKey: remotePublicKey,
  );

  /// Get the scannable encoding of this fingerprint.
  ///
  /// Returns bytes suitable for encoding in a QR code.
  Uint8List scannableEncoding();
}
