// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

/// What went wrong, as a value a caller can branch on.
///
/// One code per libsignal `SignalProtocolError` variant, so a caller never
/// needs the message text to tell two libsignal failures apart. The variant
/// payloads (counters, addresses, lengths) stay in the exception's `message`.
///
/// libsignal's `InvalidMessage` is split by its ciphertext type because "a
/// Whisper message failed to decrypt" and "a pre-key message failed to
/// decrypt" are handled differently by every session-recovery flow.
///
/// Errors this crate authors itself use the code of the libsignal condition
/// they stand for where one exists (a missing session is `sessionNotFound`
/// whichever layer noticed it), and `other` otherwise.
enum LibSignalErrorCode {
  invalidArgument,
  invalidState,
  invalidProtobufEncoding,
  ciphertextMessageTooShort,
  legacyCiphertextVersion,
  unrecognizedCiphertextVersion,
  unrecognizedMessageVersion,
  noKeyTypeIdentifier,
  badKeyType,
  badKeyLength,
  invalidKeyAgreement,
  signatureValidationFailed,
  untrustedIdentity,
  invalidPreKeyId,
  invalidSignedPreKeyId,
  invalidKyberPreKeyId,
  invalidMacKeyLength,
  noSenderKeyState,
  invalidProtocolAddress,
  sessionNotFound,
  invalidSessionStructure,
  invalidSenderKeySession,
  invalidRegistrationId,

  /// "message with old counter": a replay or a redelivery of a message whose
  /// key has already been used.
  duplicatedMessage,
  invalidWhisperMessage,
  invalidPreKeyMessage,
  invalidSenderKeyMessage,
  invalidPlaintextMessage,
  ffiBindingError,
  applicationCallbackError,
  invalidSealedSenderMessage,
  unknownSealedSenderVersion,
  sealedSenderSelfSend,
  unknownSealedSenderServerCertificateId,
  badKemKeyType,
  wrongKemKeyType,
  badKemKeyLength,
  badKemCiphertextLength,

  /// An error this crate raised that has no libsignal counterpart (argument
  /// validation, symmetric-crypto failures, internal invariants).
  other,
}

/// An error from any fallible call in this package.
///
/// `message` is the text the call used to throw as a bare `String`, unchanged.
/// Branch on `code`; show or log `message`.
class LibSignalException implements FrbException {
  final LibSignalErrorCode code;
  final String message;

  const LibSignalException({required this.code, required this.message});

  @override
  String toString() => message;

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibSignalException &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}
