// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_sender_key_distribution_inner`, `group_decrypt_inner`, `group_encrypt_inner`, `process_sender_key_distribution_inner`

/// Create a new sender key distribution message with callbacks.
///
/// This creates or updates our sender key for a group and produces a
/// distribution message that should be sent to other group members.
///
/// # Callbacks
/// - `load_sender_key(sender_name, sender_device_id, distribution_id)` - Load existing sender key
/// - `store_sender_key(sender_name, sender_device_id, distribution_id, record)` - Store updated sender key
/// - `get_identity_key_pair()` - Get our identity key pair
///
/// # Returns
/// The distribution message to send to group members.
Future<CreateSenderKeyDistributionResult>
createSenderKeyDistributionMessageWithCallbacks({
  required String senderName,
  required int senderDeviceId,
  required String distributionId,
  required FutureOr<Uint8List?> Function(String, int, String) loadSenderKey,
  required FutureOr<void> Function(String, int, String, Uint8List)
  storeSenderKey,
  required FutureOr<Uint8List> Function() getIdentityKeyPair,
}) => RustLib.instance.api
    .crateApiGroupSessionCreateSenderKeyDistributionMessageWithCallbacks(
      senderName: senderName,
      senderDeviceId: senderDeviceId,
      distributionId: distributionId,
      loadSenderKey: loadSenderKey,
      storeSenderKey: storeSenderKey,
      getIdentityKeyPair: getIdentityKeyPair,
    );

/// Process a sender key distribution message with callbacks.
///
/// This stores the sender's key so we can decrypt their messages.
///
/// # Callbacks
/// - `load_sender_key(sender_name, sender_device_id, distribution_id)` - Load existing sender key
/// - `store_sender_key(sender_name, sender_device_id, distribution_id, record)` - Store the sender key
///
/// # Returns
/// The sender key record to store.
Future<Uint8List> processSenderKeyDistributionMessageWithCallbacks({
  required String senderName,
  required int senderDeviceId,
  required String distributionId,
  required List<int> distributionMessage,
  required FutureOr<Uint8List?> Function(String, int, String) loadSenderKey,
  required FutureOr<void> Function(String, int, String, Uint8List)
  storeSenderKey,
}) => RustLib.instance.api
    .crateApiGroupSessionProcessSenderKeyDistributionMessageWithCallbacks(
      senderName: senderName,
      senderDeviceId: senderDeviceId,
      distributionId: distributionId,
      distributionMessage: distributionMessage,
      loadSenderKey: loadSenderKey,
      storeSenderKey: storeSenderKey,
    );

/// Encrypt a message to a group with callbacks.
///
/// # Callbacks
/// - `load_sender_key(sender_name, sender_device_id, distribution_id)` - Load our sender key
/// - `store_sender_key(sender_name, sender_device_id, distribution_id, record)` - Store updated sender key
/// - `get_identity_key_pair()` - Get our identity key pair (for signing)
///
/// # Returns
/// The encrypted ciphertext and updated sender key record.
Future<GroupEncryptResult> groupEncryptWithCallbacks({
  required String senderName,
  required int senderDeviceId,
  required String distributionId,
  required List<int> plaintext,
  required FutureOr<Uint8List?> Function(String, int, String) loadSenderKey,
  required FutureOr<void> Function(String, int, String, Uint8List)
  storeSenderKey,
  required FutureOr<Uint8List> Function() getIdentityKeyPair,
}) => RustLib.instance.api.crateApiGroupSessionGroupEncryptWithCallbacks(
  senderName: senderName,
  senderDeviceId: senderDeviceId,
  distributionId: distributionId,
  plaintext: plaintext,
  loadSenderKey: loadSenderKey,
  storeSenderKey: storeSenderKey,
  getIdentityKeyPair: getIdentityKeyPair,
);

/// Decrypt a message from a group member with callbacks.
///
/// # Callbacks
/// - `load_sender_key(sender_name, sender_device_id, distribution_id)` - Load the sender's key
/// - `store_sender_key(sender_name, sender_device_id, distribution_id, record)` - Store updated sender key
///
/// # Returns
/// The decrypted plaintext and updated sender key record.
Future<GroupDecryptResult> groupDecryptWithCallbacks({
  required String senderName,
  required int senderDeviceId,
  required String distributionId,
  required List<int> ciphertext,
  required FutureOr<Uint8List?> Function(String, int, String) loadSenderKey,
  required FutureOr<void> Function(String, int, String, Uint8List)
  storeSenderKey,
}) => RustLib.instance.api.crateApiGroupSessionGroupDecryptWithCallbacks(
  senderName: senderName,
  senderDeviceId: senderDeviceId,
  distributionId: distributionId,
  ciphertext: ciphertext,
  loadSenderKey: loadSenderKey,
  storeSenderKey: storeSenderKey,
);

/// Result of creating a sender key distribution message.
class CreateSenderKeyDistributionResult {
  /// The sender key distribution message to share with group members.
  final Uint8List distributionMessage;

  /// The updated sender key record to store.
  final Uint8List senderKeyRecord;

  const CreateSenderKeyDistributionResult({
    required this.distributionMessage,
    required this.senderKeyRecord,
  });

  @override
  int get hashCode => distributionMessage.hashCode ^ senderKeyRecord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateSenderKeyDistributionResult &&
          runtimeType == other.runtimeType &&
          distributionMessage == other.distributionMessage &&
          senderKeyRecord == other.senderKeyRecord;
}

/// Result of decrypting a group message.
class GroupDecryptResult {
  /// The decrypted plaintext.
  final Uint8List plaintext;

  /// The updated sender key record.
  final Uint8List senderKeyRecord;

  const GroupDecryptResult({
    required this.plaintext,
    required this.senderKeyRecord,
  });

  @override
  int get hashCode => plaintext.hashCode ^ senderKeyRecord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDecryptResult &&
          runtimeType == other.runtimeType &&
          plaintext == other.plaintext &&
          senderKeyRecord == other.senderKeyRecord;
}

/// Result of encrypting a group message.
class GroupEncryptResult {
  /// The encrypted message.
  final Uint8List ciphertext;

  /// The updated sender key record.
  final Uint8List senderKeyRecord;

  const GroupEncryptResult({
    required this.ciphertext,
    required this.senderKeyRecord,
  });

  @override
  int get hashCode => ciphertext.hashCode ^ senderKeyRecord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupEncryptResult &&
          runtimeType == other.runtimeType &&
          ciphertext == other.ciphertext &&
          senderKeyRecord == other.senderKeyRecord;
}
