// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the libsignal library.
///
/// This function is called from Dart during library initialization.
/// The library_path parameter is typically used for loading external
/// dependencies if needed.
void initLibsignal({required String libraryPath}) =>
    RustLib.instance.api.crateApiInitInitLibsignal(libraryPath: libraryPath);

/// Check if the libsignal library is initialized.
///
/// Returns true if the library has been successfully initialized.
bool isLibsignalInitialized() =>
    RustLib.instance.api.crateApiInitIsLibsignalInitialized();
