// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `from_native`, `from_native`, `native`, `native`, `native`

/// Sign an alternate identity key using separate keys.
///
/// This is a standalone version that doesn't require an IdentityKeyPair.
Uint8List identityKeypairSignAlternateIdentityRaw({
  required PublicKey publicKey,
  required PrivateKey privateKey,
  required PublicKey otherIdentity,
}) => RustLib.instance.api.crateApiKeysIdentityKeypairSignAlternateIdentityRaw(
  publicKey: publicKey,
  privateKey: privateKey,
  otherIdentity: otherIdentity,
);

/// Serialize an identity key pair from separate keys.
///
/// This is a standalone version that doesn't require an IdentityKeyPair.
Uint8List identityKeypairSerializeRaw({
  required PublicKey publicKey,
  required PrivateKey privateKey,
}) => RustLib.instance.api.crateApiKeysIdentityKeypairSerializeRaw(
  publicKey: publicKey,
  privateKey: privateKey,
);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IdentityKeyPair>>
abstract class IdentityKeyPair implements RustOpaqueInterface {
  /// Deserialize an identity key pair from bytes.
  ///
  /// # Security
  /// The input bytes are securely zeroized after deserialization.
  static IdentityKeyPair deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKeysIdentityKeyPairDeserialize(bytes: bytes);

  /// Create an identity key pair from existing keys.
  static IdentityKeyPair fromKeys({
    required PrivateKey privateKey,
    required PublicKey publicKey,
  }) => RustLib.instance.api.crateApiKeysIdentityKeyPairFromKeys(
    privateKey: privateKey,
    publicKey: publicKey,
  );

  /// Generate a new identity key pair.
  static IdentityKeyPair generate() =>
      RustLib.instance.api.crateApiKeysIdentityKeyPairGenerate();

  /// Get the private key as serialized bytes.
  ///
  /// # Security
  /// The returned bytes contain sensitive private key material.
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  ///
  /// If all you need is a signature by the identity key — signing a signed
  /// pre-key or a Kyber pre-key, say — call `identityKeyPair.sign` instead.
  /// It does the same work without copying the long-term secret out of Rust.
  Uint8List get privateKey;

  /// Get the public key as serialized bytes.
  Uint8List get publicKey;

  /// Serialize this identity key pair.
  ///
  /// # Security
  /// The returned bytes contain sensitive key material (including the private key).
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List serialize();

  /// Sign a message with this identity key pair's private key.
  ///
  /// This is how a signed pre-key or a Kyber pre-key gets its identity-key
  /// signature, which is what X3DH requires of a published pre-key bundle.
  ///
  /// # Security
  /// Prefer this over reading the `privateKey` getter and rebuilding a
  /// `PrivateKey` from those bytes. The getter copies the long-term identity
  /// secret into the Dart heap, where nothing can zeroize it and it survives
  /// until the garbage collector happens to reclaim it; this method keeps the
  /// secret in Rust for the whole operation.
  ///
  /// It grants no capability the pair did not already have — signing
  /// arbitrary bytes with the identity key is reachable through that same
  /// `privateKey` getter today. It removes a copy of the secret, nothing else.
  ///
  /// Signatures made here are not interchangeable with those from
  /// `signAlternateIdentity`, which signs a domain-separated message rather
  /// than the bytes it is given: a fixed 32-byte prefix and a label precede
  /// the other identity key. A serialized public key cannot begin with that
  /// prefix, so the two uses of the identity key overlap only if a caller
  /// deliberately builds the prefix and passes it as `message`.
  Uint8List sign({required List<int> message});

  /// Sign an alternate identity key.
  ///
  /// This is used in the multi-device protocol to link devices.
  Uint8List signAlternateIdentity({required PublicKey otherIdentity});
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PrivateKey>>
abstract class PrivateKey implements RustOpaqueInterface {
  /// Perform X25519 key agreement with a public key.
  ///
  /// This is the raw Diffie-Hellman primitive and nothing more: 32 bytes out,
  /// no derivation, no ratchet, no replay protection. Ordinary Signal
  /// Protocol use never needs it — `SessionBuilder` and `SessionCipher`
  /// perform every agreement the protocol calls for, together with the
  /// derivation and ratcheting that make those agreements safe. Reach for
  /// this only when building a protocol this package does not implement.
  ///
  /// # Security
  /// The returned shared secret is highly sensitive cryptographic material.
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  ///
  /// **The result is not a key.** X25519 returns the x-coordinate of a curve
  /// point, which is a field element rather than a uniformly distributed
  /// 32-byte string, so using it directly to encrypt is a mistake even though
  /// the bytes look random. Put it through a KDF first and use that output —
  /// `hkdfDerive` on this same surface takes it as `inputKeyMaterial`.
  ///
  /// One agreement between two long-lived keys yields the same secret every
  /// time it is computed, so on its own this offers no forward secrecy: a
  /// private key compromised later opens everything ever derived from it.
  /// Forward secrecy comes from ratcheting over ephemeral keys, which is what
  /// the session API does and what a caller of this method must build.
  ///
  /// An all-zero shared secret — what a low-order public key produces — is
  /// rejected in constant time and surfaces as a thrown error rather than as
  /// 32 zero bytes. That check catches the degenerate result only; validating
  /// that the peer's public key is the one expected remains the caller's job,
  /// and this method authenticates nothing.
  Uint8List agree({required PublicKey publicKey});

  /// Create a copy of this private key.
  ///
  /// # Security
  /// This duplicates sensitive secret key material into a second independent
  /// object. Each copy holds the secret in native memory until it is dropped,
  /// so every copy must be handled with the same care as the original.
  /// In security-critical applications, call `dispose()` on the Dart side of
  /// each copy as soon as it is no longer needed rather than waiting for the
  /// garbage collector, and avoid making copies you do not need.
  PrivateKey cloneKey();

  /// Deserialize a private key from bytes.
  ///
  /// # Security
  /// The input bytes are securely zeroized after deserialization.
  static PrivateKey deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKeysPrivateKeyDeserialize(bytes: bytes);

  /// Generate a new random private key.
  static PrivateKey generate() =>
      RustLib.instance.api.crateApiKeysPrivateKeyGenerate();

  /// Get the public key corresponding to this private key.
  PublicKey getPublicKey();

  /// Serialize this private key to bytes.
  ///
  /// # Security
  /// The returned bytes contain sensitive key material. The caller is responsible
  /// for securely zeroing these bytes when done. Consider using `SecureBytes.wrap()`
  /// on the Dart side to ensure automatic zeroing.
  Uint8List serialize();

  /// Sign a message with this private key.
  Uint8List sign({required List<int> message});
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PublicKey>>
abstract class PublicKey implements RustOpaqueInterface {
  /// Create a copy of this public key.
  PublicKey cloneKey();

  /// Compare this public key with another.
  ///
  /// Comparison is performed lexicographically on the serialized bytes.
  int compare({required PublicKey other});

  /// Deserialize a public key from bytes.
  static PublicKey deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKeysPublicKeyDeserialize(bytes: bytes);

  /// Check if this public key equals another.
  bool equals({required PublicKey other});

  /// Get the raw public key bytes without the type prefix.
  Uint8List getPublicKeyBytes();

  /// Serialize this public key to bytes.
  Uint8List serialize();

  /// Verify a signature on a message.
  bool verify({required List<int> message, required List<int> signature});
}
