// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `from_native`, `from_native`, `from_native`, `native`, `native`, `native`, `native`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KyberKeyPair>>
abstract class KyberKeyPair implements RustOpaqueInterface {
  /// Clone this Kyber key pair.
  ///
  /// # Security
  /// This duplicates the pair's sensitive secret key material into a second
  /// independent object. Each copy holds the secret in native memory until it
  /// is dropped, so every copy must be handled with the same care as the
  /// original. In security-critical applications, call `dispose()` on the Dart
  /// side of each copy as soon as it is no longer needed rather than waiting
  /// for the garbage collector, and avoid making copies you do not need.
  KyberKeyPair cloneKey();

  /// Create a Kyber key pair from its two halves.
  ///
  /// For keys stored apart: each half has its own serialized form,
  /// `KyberPublicKey.serialize()` and `KyberSecretKey.serialize()`, while the
  /// pair has none — upstream libsignal defines no encoding for it. Deserialize
  /// both halves and join them here to get the key pair
  /// `KyberPreKeyRecord.create` takes. A Kyber pre-key kept whole needs none of
  /// this: `KyberPreKeyRecord.serialize()` carries both halves together with
  /// the id, timestamp and signature.
  ///
  /// The halves are checked to belong together: a shared secret encapsulated
  /// to `publicKey` has to decapsulate to the same value under `secretKey`.
  /// That is stricter than upstream libsignal, which compares only the key
  /// types, and nothing later would catch a mismatch. Creating a record and
  /// reading it back do not check the pairing, and decapsulating under the
  /// wrong secret key does not fail — it yields a different shared secret. A
  /// record built from mismatched halves would be accepted and published, and
  /// the mismatch would surface only when a peer's first message failed to
  /// decrypt, with nothing pointing back to this call.
  ///
  /// # Errors
  /// Fails if the two keys are for different KEM types, or are not halves of
  /// the same key pair.
  ///
  /// # Security
  /// Unlike `IdentityKeyPair.fromKeys`, this consumes neither argument: the
  /// pair holds its own copy of the secret key, and the `KyberSecretKey` passed
  /// in stays valid. Call `dispose()` on it as soon as it is no longer needed
  /// rather than waiting for the garbage collector — as with `cloneKey()`, each
  /// copy keeps the secret in native memory until it is dropped, and dropping
  /// does not wipe it.
  static KyberKeyPair fromKeys({
    required KyberPublicKey publicKey,
    required KyberSecretKey secretKey,
  }) => RustLib.instance.api.crateApiKyberKyberKeyPairFromKeys(
    publicKey: publicKey,
    secretKey: secretKey,
  );

  /// Generate a new random Kyber key pair.
  static KyberKeyPair generate() =>
      RustLib.instance.api.crateApiKyberKyberKeyPairGenerate();

  /// Get the public key from this key pair.
  KyberPublicKey getPublicKey();

  /// Get the secret key from this key pair.
  ///
  /// # Security
  /// The returned key contains sensitive secret key material. When serialized,
  /// the caller is responsible for securely zeroing those bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side after serialization.
  KyberSecretKey getSecretKey();
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KyberPreKeyRecord>>
abstract class KyberPreKeyRecord implements RustOpaqueInterface {
  /// Clone this Kyber pre-key record.
  KyberPreKeyRecord cloneRecord();

  /// Create a new Kyber pre-key record.
  static KyberPreKeyRecord create({
    required int id,
    required BigInt timestamp,
    required KyberKeyPair keyPair,
    required List<int> signature,
  }) => RustLib.instance.api.crateApiKyberKyberPreKeyRecordCreate(
    id: id,
    timestamp: timestamp,
    keyPair: keyPair,
    signature: signature,
  );

  /// Deserialize a Kyber pre-key record from bytes.
  ///
  /// # Security
  /// The input bytes are securely zeroized after deserialization.
  static KyberPreKeyRecord deserialize({required List<int> bytes}) => RustLib
      .instance
      .api
      .crateApiKyberKyberPreKeyRecordDeserialize(bytes: bytes);

  /// Get the key pair from this Kyber pre-key record.
  KyberKeyPair getKeyPair();

  /// Get the public key from this Kyber pre-key record.
  KyberPublicKey getPublicKey();

  /// Get the secret key from this Kyber pre-key record.
  ///
  /// # Security
  /// The returned key contains sensitive secret key material. When serialized,
  /// the caller is responsible for securely zeroing those bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side after serialization.
  KyberSecretKey getSecretKey();

  /// Get the ID of this Kyber pre-key record.
  int id();

  /// Serialize this Kyber pre-key record to bytes.
  ///
  /// # Security
  /// The returned bytes contain sensitive key material (including the secret key).
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List serialize();

  /// Get the signature of this Kyber pre-key record.
  Uint8List signature();

  /// Get the timestamp of this Kyber pre-key record.
  BigInt timestamp();
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KyberPublicKey>>
abstract class KyberPublicKey implements RustOpaqueInterface {
  /// Clone this Kyber public key.
  KyberPublicKey cloneKey();

  /// Deserialize a Kyber public key from bytes.
  static KyberPublicKey deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKyberKyberPublicKeyDeserialize(bytes: bytes);

  /// Check if this Kyber public key equals another.
  bool equals({required KyberPublicKey other});

  /// Serialize this Kyber public key to bytes.
  Uint8List serialize();
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KyberSecretKey>>
abstract class KyberSecretKey implements RustOpaqueInterface {
  /// Clone this Kyber secret key.
  ///
  /// # Security
  /// This duplicates sensitive secret key material into a second independent
  /// object. Each copy holds the secret in native memory until it is dropped,
  /// so every copy must be handled with the same care as the original.
  /// In security-critical applications, call `dispose()` on the Dart side of
  /// each copy as soon as it is no longer needed rather than waiting for the
  /// garbage collector, and avoid making copies you do not need.
  KyberSecretKey cloneKey();

  /// Deserialize a Kyber secret key from bytes.
  ///
  /// # Security
  /// The input bytes are securely zeroized after deserialization.
  static KyberSecretKey deserialize({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKyberKyberSecretKeyDeserialize(bytes: bytes);

  /// Serialize this Kyber secret key to bytes.
  ///
  /// # Security
  /// The returned bytes contain sensitive secret key material.
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List serialize();
}
