// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `message_decrypt_prekey_inner`, `message_decrypt_signal_inner`, `message_encrypt_inner`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PreKeyDecryptOutcome`

/// Extract pre-key IDs from a serialized pre-key message.
PreKeyMessageIds extractPrekeyMessageIds({required List<int> message}) =>
    RustLib.instance.api.crateApiSessionCipherExtractPrekeyMessageIds(
      message: message,
    );

/// Encrypt a message using an established session with DartFn callbacks.
///
/// # Callbacks
/// - `load_session(name, device_id)` - Load the session record
/// - `store_session(name, device_id, record)` - Store the updated session record
/// - `get_identity_key_pair()` - Get our serialized identity key pair
/// - `get_local_registration_id()` - Get our registration ID
///
/// # Parameters
/// - `local_name` - Our user identifier (UUID)
/// - `local_device_id` - Our device ID
Future<EncryptResult> messageEncryptWithCallbacks({
  required String remoteName,
  required int remoteDeviceId,
  required String localName,
  required int localDeviceId,
  required List<int> plaintext,
  required FutureOr<Uint8List?> Function(String, int) loadSession,
  required FutureOr<void> Function(String, int, Uint8List) storeSession,
  required FutureOr<Uint8List> Function() getIdentityKeyPair,
  required FutureOr<int> Function() getLocalRegistrationId,
  required FutureOr<Uint8List?> Function(String, int) getIdentity,
}) => RustLib.instance.api.crateApiSessionCipherMessageEncryptWithCallbacks(
  remoteName: remoteName,
  remoteDeviceId: remoteDeviceId,
  localName: localName,
  localDeviceId: localDeviceId,
  plaintext: plaintext,
  loadSession: loadSession,
  storeSession: storeSession,
  getIdentityKeyPair: getIdentityKeyPair,
  getLocalRegistrationId: getLocalRegistrationId,
  getIdentity: getIdentity,
);

/// Decrypt a Signal message (not a pre-key message) with DartFn callbacks.
///
/// # Callbacks
/// - `load_session(name, device_id)` - Load the session record
/// - `store_session(name, device_id, record)` - Store the updated session record
/// - `get_identity_key_pair()` - Get our serialized identity key pair
/// - `get_local_registration_id()` - Get our registration ID
/// - `save_identity(name, device_id, identity_key)` - Save the remote identity key
///
/// # Parameters
/// - `local_name` - Our user identifier (UUID)
/// - `local_device_id` - Our device ID
Future<Uint8List> messageDecryptSignalWithCallbacks({
  required String remoteName,
  required int remoteDeviceId,
  required String localName,
  required int localDeviceId,
  required List<int> ciphertext,
  required FutureOr<Uint8List?> Function(String, int) loadSession,
  required FutureOr<void> Function(String, int, Uint8List) storeSession,
  required FutureOr<Uint8List> Function() getIdentityKeyPair,
  required FutureOr<int> Function() getLocalRegistrationId,
  required FutureOr<void> Function(String, int, Uint8List) saveIdentity,
  required FutureOr<Uint8List?> Function(String, int) getIdentity,
}) =>
    RustLib.instance.api.crateApiSessionCipherMessageDecryptSignalWithCallbacks(
      remoteName: remoteName,
      remoteDeviceId: remoteDeviceId,
      localName: localName,
      localDeviceId: localDeviceId,
      ciphertext: ciphertext,
      loadSession: loadSession,
      storeSession: storeSession,
      getIdentityKeyPair: getIdentityKeyPair,
      getLocalRegistrationId: getLocalRegistrationId,
      saveIdentity: saveIdentity,
      getIdentity: getIdentity,
    );

/// Decrypt a pre-key Signal message (first message in a new session) with DartFn callbacks.
///
/// # Callbacks
/// - `load_session(name, device_id)` - Load existing session record (may be None)
/// - `store_session(name, device_id, record)` - Store the new session record
/// - `get_identity_key_pair()` - Get our serialized identity key pair
/// - `get_local_registration_id()` - Get our registration ID
/// - `save_identity(name, device_id, identity_key)` - Save the remote identity key
/// - `load_signed_pre_key(id)` - Load a signed pre-key by ID (may return None if not found)
/// - `load_pre_key(id)` - Load a one-time pre-key by ID (may return None)
/// - `remove_pre_key(id)` - Remove a used one-time pre-key
/// - `load_kyber_pre_key(id)` - Load a Kyber pre-key by ID (may return None)
/// - `mark_kyber_pre_key_used(kyber_id, signed_pre_key_id, base_key)` - Mark a
///   Kyber pre-key as used. The three arguments mirror libsignal's
///   `KyberPreKeyStore::mark_kyber_pre_key_used`, so a store can implement the
///   last-resort anti-replay check that trait documents.
///
/// # Write ordering
/// The write-back callbacks run in libsignal's own order — `save_identity`,
/// `mark_kyber_pre_key_used`, `remove_pre_key`, then `store_session` last. The
/// session must land after the consumption writes: if it landed first and the
/// process died before them, the redelivered message would match the
/// now-persisted session, consume nothing, and leave the pre-keys usable.
///
/// # Parameters
/// - `local_name` - Our user identifier (UUID)
/// - `local_device_id` - Our device ID
Future<Uint8List> messageDecryptPrekeyWithCallbacks({
  required String remoteName,
  required int remoteDeviceId,
  required String localName,
  required int localDeviceId,
  required List<int> ciphertext,
  required FutureOr<Uint8List?> Function(String, int) loadSession,
  required FutureOr<void> Function(String, int, Uint8List) storeSession,
  required FutureOr<Uint8List> Function() getIdentityKeyPair,
  required FutureOr<int> Function() getLocalRegistrationId,
  required FutureOr<void> Function(String, int, Uint8List) saveIdentity,
  required FutureOr<Uint8List?> Function(int) loadSignedPreKey,
  required FutureOr<Uint8List?> Function(int) loadPreKey,
  required FutureOr<void> Function(int) removePreKey,
  required FutureOr<Uint8List?> Function(int) loadKyberPreKey,
  required FutureOr<void> Function(int, int, Uint8List) markKyberPreKeyUsed,
  required FutureOr<Uint8List?> Function(String, int) getIdentity,
}) =>
    RustLib.instance.api.crateApiSessionCipherMessageDecryptPrekeyWithCallbacks(
      remoteName: remoteName,
      remoteDeviceId: remoteDeviceId,
      localName: localName,
      localDeviceId: localDeviceId,
      ciphertext: ciphertext,
      loadSession: loadSession,
      storeSession: storeSession,
      getIdentityKeyPair: getIdentityKeyPair,
      getLocalRegistrationId: getLocalRegistrationId,
      saveIdentity: saveIdentity,
      loadSignedPreKey: loadSignedPreKey,
      loadPreKey: loadPreKey,
      removePreKey: removePreKey,
      loadKyberPreKey: loadKyberPreKey,
      markKyberPreKeyUsed: markKyberPreKeyUsed,
      getIdentity: getIdentity,
    );

/// Result of encrypting a message.
class EncryptResult {
  /// The ciphertext type (1 = Signal message, 3 = Pre-key message).
  final int messageType;

  /// The encrypted message bytes.
  final Uint8List ciphertext;

  const EncryptResult({required this.messageType, required this.ciphertext});

  @override
  int get hashCode => messageType.hashCode ^ ciphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptResult &&
          runtimeType == other.runtimeType &&
          messageType == other.messageType &&
          ciphertext == other.ciphertext;
}

/// Pre-key IDs extracted from a pre-key message.
class PreKeyMessageIds {
  /// The one-time pre-key ID (if present).
  final int? preKeyId;

  /// The signed pre-key ID.
  final int signedPreKeyId;

  /// The Kyber pre-key ID (if present).
  final int? kyberPreKeyId;

  const PreKeyMessageIds({
    this.preKeyId,
    required this.signedPreKeyId,
    this.kyberPreKeyId,
  });

  @override
  int get hashCode =>
      preKeyId.hashCode ^ signedPreKeyId.hashCode ^ kyberPreKeyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreKeyMessageIds &&
          runtimeType == other.runtimeType &&
          preKeyId == other.preKeyId &&
          signedPreKeyId == other.signedPreKeyId &&
          kyberPreKeyId == other.kyberPreKeyId;
}
