// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'keys.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `native_mut`, `native`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SessionRecord>>
abstract class SessionRecord implements RustOpaqueInterface {
  /// Archive the current session state.
  void archiveCurrentState();

  /// Create a copy of this session record.
  SessionRecord cloneRecord();

  /// Check if the current ratchet key matches the given public key.
  bool currentRatchetKeyMatches({required PublicKey key});

  /// Deserialize a session record from bytes.
  ///
  /// # Security
  /// The input bytes are securely zeroized after deserialization.
  static SessionRecord deserialize({required List<int> bytes}) => RustLib
      .instance
      .api
      .crateApiSessionSessionRecordDeserialize(bytes: bytes);

  /// Check if this session has a usable sender chain.
  bool hasUsableSenderChain({required BigInt nowMillis});

  /// Get the local registration ID.
  int localRegistrationId();

  /// Get the remote registration ID.
  int remoteRegistrationId();

  /// Serialize this session record to bytes.
  ///
  /// # Security
  /// The returned bytes contain sensitive session state (including ratchet keys).
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List serialize();
}
