// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'bundle.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `process_prekey_bundle_inner`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProcessPreKeyBundleResult`

/// Process a pre-key bundle to establish a new session with DartFn callbacks.
///
/// This function establishes a session with a remote user using their pre-key bundle.
/// Store operations are performed via callbacks to the Dart side.
///
/// # Callbacks
/// - `load_session(name, device_id)` - Load existing session record
/// - `store_session(name, device_id, record)` - Store the new session record
/// - `get_identity_key_pair()` - Get our serialized identity key pair
/// - `get_local_registration_id()` - Get our registration ID
/// - `save_identity(name, device_id, identity_key)` - Save the remote identity key
///
/// # Parameters
/// - `local_name` - Our user identifier (UUID)
/// - `local_device_id` - Our device ID
///
/// # Returns
/// The result containing the new session record and identity to save.
Future<void> processPrekeyBundleWithCallbacks({
  required String remoteName,
  required int remoteDeviceId,
  required String localName,
  required int localDeviceId,
  required PreKeyBundle bundle,
  required FutureOr<Uint8List?> Function(String, int) loadSession,
  required FutureOr<void> Function(String, int, Uint8List) storeSession,
  required FutureOr<Uint8List> Function() getIdentityKeyPair,
  required FutureOr<int> Function() getLocalRegistrationId,
  required FutureOr<void> Function(String, int, Uint8List) saveIdentity,
  required FutureOr<Uint8List?> Function(String, int) getIdentity,
}) =>
    RustLib.instance.api.crateApiSessionBuilderProcessPrekeyBundleWithCallbacks(
      remoteName: remoteName,
      remoteDeviceId: remoteDeviceId,
      localName: localName,
      localDeviceId: localDeviceId,
      bundle: bundle,
      loadSession: loadSession,
      storeSession: storeSession,
      getIdentityKeyPair: getIdentityKeyPair,
      getLocalRegistrationId: getLocalRegistrationId,
      saveIdentity: saveIdentity,
      getIdentity: getIdentity,
    );
