// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'keys.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `native`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SignedPreKeyRecord>>
abstract class SignedPreKeyRecord implements RustOpaqueInterface {
  /// Deserialize a signed pre-key record from bytes.
  ///
  /// # Security
  /// The input bytes are securely zeroized after deserialization.
  static SignedPreKeyRecord deserialize({required List<int> bytes}) => RustLib
      .instance
      .api
      .crateApiSignedPrekeySignedPreKeyRecordDeserialize(bytes: bytes);

  /// Get the signed pre-key ID.
  int id();

  /// Create a new signed pre-key record.
  ///
  /// # Arguments
  /// * `id` - The signed pre-key identifier
  /// * `timestamp` - The timestamp when this key was generated (milliseconds since epoch)
  /// * `public_key` - The public key
  /// * `private_key` - The private key
  /// * `signature` - The signature of the public key by the identity key
  factory SignedPreKeyRecord({
    required int id,
    required BigInt timestamp,
    required PublicKey publicKey,
    required PrivateKey privateKey,
    required List<int> signature,
  }) => RustLib.instance.api.crateApiSignedPrekeySignedPreKeyRecordNew(
    id: id,
    timestamp: timestamp,
    publicKey: publicKey,
    privateKey: privateKey,
    signature: signature,
  );

  /// Get the private key.
  ///
  /// # Security
  /// The returned bytes contain sensitive private key material.
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List privateKey();

  /// Get the public key.
  Uint8List publicKey();

  /// Serialize this signed pre-key record to bytes.
  ///
  /// # Security
  /// The returned bytes contain sensitive key material (including the private key).
  /// The caller is responsible for securely zeroing these bytes when done.
  /// Consider using `SecureBytes.wrap()` on the Dart side to ensure automatic zeroing.
  Uint8List serialize();

  /// Get the signature.
  Uint8List signature();

  /// Get the timestamp when this key was generated.
  BigInt timestamp();
}
